### PR TITLE
feat: Customisable right padding of the track after maximumValue

### PR DESCRIPTION
**Pull request by RobertMetcalfePhorest**
# Description

This PR addresses the issue described here: https://github.com/miblanchard/react-native-slider/issues/345

The proposed solution consists of adding a property that will let users specify the `trackRightPadding` instead of always using the `thumbSize.width`

# Before

Screenshot_2022-08-08_at_14_16_12

# After

Screenshot 2022-08-08 at 14 15 42

### CODE REVIEW

**Comment by hugoh59** [comment]
This is a super basic feature, how is this still not adressed ? Can we prioritize this issue ?

**Review by nekiro — APPROVED** [review]

**Review by fabio-alss-freitas — APPROVED** [review]

**Review by atesarova — APPROVED** [review]

**Comment by brycnguyen** [comment]
Is this going to be merged soon?

**Review by miblanchard — COMMENTED** [review]
Sorry for the slow review.  Can you please add a use case to the Storybook story examples that uses this prop for reference?

**Review by miblanchard — APPROVED** [review]
I'm ok merging this for now, but could you add the example as well, please?

**Comment by miblanchard** [comment]
@RobertMetcalfePhorest - Looks like there are some merge conflicts now.  Can you resolve?  Then I will merge and publish.

**Comment by mikespence** [comment]
Great fix! When will this be merged?

**Review by miblanchard — APPROVED** [review]

**Comment by miblanchard** [comment]
@mikespence - We need @RobertMetcalfePhorest to resolve the merge conflicts before we can merge.

**Comment by RobertMetcalfePhorest** [comment]
@miblanchard Resolved the conflict

**Comment by nbodesa** [comment]
Can this be merged please?

**Comment by MattinNajafi** [comment]
@miblanchard I still have this issue, I have downloaded version 2.3.1 and its still there. Or should i do something else to fix this issue?

**Comment by voidsatisfaction** [comment]
When this PR release? I also have this troble with 2.3.1

**Pull request merged**
