### PR TITLE
fix rtl issue

### PR DESCRIPTION
**Pull request by Venon-IT**
Sorry I am not good with git. So I deleted my forked repository and forked again from main repository after that I fixed issue.

### CODE REVIEW

**Review by miblanchard — APPROVED** [review]
Code looks good and no regressions for LTR - I don't have a good setup for RTL testing at the moment so I'll trust that it fixed the problem for you!

**Comment by Venon-IT** [comment]
I tested for LTR and RTL both and tested how react code when direction change on runtime. It's look good. I tested with one and two mark. I did not encounter any issue and thx for merge. have a good day

**Comment by miblanchard** [comment]
@Venon-IT thanks again for fixing the issue!

**Comment by miblanchard** [comment]
v1.5.0 should include your fix

**Pull request merged**
