### PR TITLE
feat: Return of the index from the thumb callback renderer

### PR DESCRIPTION
**Pull request by somersets**
It would be nice to get an index on the thumb function renderer to understand where the left thumb and right thumb are

### CODE REVIEW

**Review by miblanchard — COMMENTED** [review]
Could you please also update the README to indicate this parameter is now being passed?

**Comment by somersets** [comment]
@miblanchard Sure, I'll add it now.

**Review by miblanchard — APPROVED** [review]
thanks!

**Comment by somersets** [comment]
@miblanchard Hi, why can't you merge this branch?

**Comment by somersets** [comment]
thanks!

**Pull request merged**
